# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
lang: es

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Europe/Madrid

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: D4rkh45h's Blog
tagline: Escribiendo sobre ciberseguridad, hacking y retos.
description: >- # usado por los meta de SEO y el feed atom
  Un blog dedicado a la ciberseguridad, writeups de Hack The Box y VulnHub, y mi viaje en el mundo del hacking ofensivo.

# Rellena el protocolo y el hostname de tu sitio.
# ¡IMPORTANTE para sitios de proyecto!
# 'url' debe ser la URL base de tu usuario de GitHub Pages (sin el nombre del repositorio).
# 'baseurl' debe ser el nombre de tu repositorio de proyecto (con barra inicial).
url: "https://d4rkh45h.github.io" # La URL de tu sitio de usuario base
github:
  username: d4rkh45h # Tu usuario de GitHub

twitter:
  username: # Dejado vacío

social:
  name: D4rkh45h # Tu nombre o alias
  email: drkhsh8@gmail.com # Tu dirección de correo
  links:
    - https://github.com/d4rkh45h # Tu perfil de GitHub
    - https://www.linkedin.com/in/pedro-jos%C3%A9-461479353/ # Tu perfil de LinkedIn

# Site Verification Settings (rellena si usas estos servicios)
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# ↑ --------------------------
# El final de la configuración `jekyll-seo-tag`

# Web Analytics Settings (rellena si usas estos servicios)
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page views settings
pageviews:
  provider: # [goatcounter]

# Prefer color scheme setting.
# Deja vacío para seguir la configuración del sistema, con un botón para cambiar entre claro/oscuro.
# theme_mode: # [light | dark]

# The CDN endpoint for media resources.
cdn:

# The avatar on sidebar, support local or CORS resources
avatar: /assets/img/profile.png # Asegúrate de que esta imagen exista en esa ruta

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
social_preview_image:

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  provider: # [disqus | utterances | giscus] (rellena uno si quieres comentarios)
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

# The base URL of your site
# ¡Crucial para tu sitio de proyecto "Offsec"! Debe ser el nombre del repositorio.
baseurl: "/Offsec"

# ------------------ Content Security Policy (CSP) -------------------
# Descomenta y ajusta las directivas CSP para permitir los recursos.
# El tema Chirpy usa una CSP estricta por defecto si no se especifica.
# Ref: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md#content-security-policy
# Nota: 'unsafe-inline' es a menudo necesario para estilos y scripts inyectados por Jekyll/temas.
#       'data:' es crucial para fuentes incrustadas.
#       Ajusta los CDNs según los que realmente uses.
csp:
  enabled: true
  default_src: "'self'"
  script_src: "'self' https://cdn.jsdelivr.net"
  style_src: "'self' 'unsafe-inline' https://cdn.jsdelivr.net"
  img_src: "'self' data: https://www.google-analytics.com https://cdn.jsdelivr.net"
  font_src: "'self' data: https://cdn.jsdelivr.net"
  connect_src: "'self' https://www.google-analytics.com"
# --------------------------------------------------------------------

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/